### ISSUE TITLE
how big is the data? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [google/youtube-8m#122]
for these two? The website doesn't mention it. On kaggle it says. 1TB+ 

If the below is beyond a 100GB. Is there anyway to use a subset? 

curl data.yt8m.org/download.py | partition=3/frame/validate mirror=us python
curl data.yt8m.org/download.py | partition=3/frame/test mirror=us python

**Comment by LeegleechN** [comment]
The info is on the [download page](https://research.google.com/youtube8m/download.html).
The frame features dataset is 1.53TB and the video features dataset is 31GB. That page also has instructions for how to download a subset of the data. Here is an example command line to download 1/100 of the data:

` 
curl data.yt8m.org/download.py | shard=1,100 partition=2/video/train mirror=us python 
`

In the future, please use the [google group](https://groups.google.com/forum/#!forum/youtube8m-users) for these kinds of questions rather than opening issues on github.
